/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCommunityIdRouteImport } from './routes/app.community.$id'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppTenantsIdRouteImport } from './routes/app.tenants.$id'
import { Route as AppMessagesIdRouteImport } from './routes/app.messages.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIdRoute = AppTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTenantsRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppCommunityIdRoute = AppCommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/community/$id': typeof AppCommunityIdRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/tenants/$id': typeof AppTenantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/community/$id': typeof AppCommunityIdRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/tenants/$id': typeof AppTenantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/community': typeof AppCommunityRoute
  '/app/community/$id': typeof AppCommunityIdRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/people': typeof AppPeopleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tenants': typeof AppTenantsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/tenants/$id': typeof AppTenantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/assistant'
    | '/app/community'
    | '/app/community/$id'
    | '/app/messages'
    | '/app/people'
    | '/app/settings'
    | '/app/tenants'
    | '/app/'
    | '/app/messages/$id'
    | '/app/tenants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/assistant'
    | '/app/community'
    | '/app/community/$id'
    | '/app/messages'
    | '/app/people'
    | '/app/settings'
    | '/app/tenants'
    | '/app'
    | '/app/messages/$id'
    | '/app/tenants/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/assistant'
    | '/app/community'
    | '/app/community/$id'
    | '/app/messages'
    | '/app/people'
    | '/app/settings'
    | '/app/tenants'
    | '/app/'
    | '/app/messages/$id'
    | '/app/tenants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/$id': {
      id: '/app/community/$id'
      path: '/$id'
      fullPath: '/app/community/$id'
      preLoaderRoute: typeof AppCommunityIdRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants/$id': {
      id: '/app/tenants/$id'
      path: '/$id'
      fullPath: '/app/tenants/$id'
      preLoaderRoute: typeof AppTenantsIdRouteImport
      parentRoute: typeof AppTenantsRoute
    }
    '/app/messages/$id': {
      id: '/app/messages/$id'
      path: '/$id'
      fullPath: '/app/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
  }
}

interface AppMessagesRouteChildren {
  AppMessagesIdRoute: typeof AppMessagesIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesIdRoute: AppMessagesIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppTenantsRouteChildren {
  AppTenantsIdRoute: typeof AppTenantsIdRoute
}

const AppTenantsRouteChildren: AppTenantsRouteChildren = {
  AppTenantsIdRoute: AppTenantsIdRoute,
}

const AppTenantsRouteWithChildren = AppTenantsRoute._addFileChildren(
  AppTenantsRouteChildren,
)

interface AppCommunityRouteChildren {
  AppCommunityIdRoute: typeof AppCommunityIdRoute
}

const AppCommunityRouteChildren: AppCommunityRouteChildren = {
  AppCommunityIdRoute: AppCommunityIdRoute,
}

const AppCommunityRouteWithChildren = AppCommunityRoute._addFileChildren(
  AppCommunityRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCommunityRoute: typeof AppCommunityRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppPeopleRoute: typeof AppPeopleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTenantsRoute: typeof AppTenantsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCommunityRoute: AppCommunityRouteWithChildren,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppPeopleRoute: AppPeopleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTenantsRoute: AppTenantsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
