/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as RentRouteImport } from './routes/rent'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantUtilitiesRouteImport } from './routes/tenant.utilities'
import { Route as TenantNoticesRouteImport } from './routes/tenant.notices'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant.maintenance'
import { Route as TenantBillingRouteImport } from './routes/tenant.billing'

const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantUtilitiesRoute = TenantUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => TenantRoute,
} as any)
const TenantNoticesRoute = TenantNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBillingRoute = TenantBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/maintenance': typeof MaintenanceRoute
  '/notices': typeof NoticesRoute
  '/rent': typeof RentRoute
  '/tenant': typeof TenantRouteWithChildren
  '/tenants': typeof TenantsRoute
  '/utilities': typeof UtilitiesRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/notices': typeof TenantNoticesRoute
  '/tenant/utilities': typeof TenantUtilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/maintenance': typeof MaintenanceRoute
  '/notices': typeof NoticesRoute
  '/rent': typeof RentRoute
  '/tenant': typeof TenantRouteWithChildren
  '/tenants': typeof TenantsRoute
  '/utilities': typeof UtilitiesRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/notices': typeof TenantNoticesRoute
  '/tenant/utilities': typeof TenantUtilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/maintenance': typeof MaintenanceRoute
  '/notices': typeof NoticesRoute
  '/rent': typeof RentRoute
  '/tenant': typeof TenantRouteWithChildren
  '/tenants': typeof TenantsRoute
  '/utilities': typeof UtilitiesRoute
  '/tenant/billing': typeof TenantBillingRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/notices': typeof TenantNoticesRoute
  '/tenant/utilities': typeof TenantUtilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/building'
    | '/calendar'
    | '/dashboard'
    | '/maintenance'
    | '/notices'
    | '/rent'
    | '/tenant'
    | '/tenants'
    | '/utilities'
    | '/tenant/billing'
    | '/tenant/maintenance'
    | '/tenant/notices'
    | '/tenant/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/building'
    | '/calendar'
    | '/dashboard'
    | '/maintenance'
    | '/notices'
    | '/rent'
    | '/tenant'
    | '/tenants'
    | '/utilities'
    | '/tenant/billing'
    | '/tenant/maintenance'
    | '/tenant/notices'
    | '/tenant/utilities'
  id:
    | '__root__'
    | '/'
    | '/building'
    | '/calendar'
    | '/dashboard'
    | '/maintenance'
    | '/notices'
    | '/rent'
    | '/tenant'
    | '/tenants'
    | '/utilities'
    | '/tenant/billing'
    | '/tenant/maintenance'
    | '/tenant/notices'
    | '/tenant/utilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingRoute: typeof BuildingRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NoticesRoute: typeof NoticesRoute
  RentRoute: typeof RentRoute
  TenantRoute: typeof TenantRouteWithChildren
  TenantsRoute: typeof TenantsRoute
  UtilitiesRoute: typeof UtilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/utilities': {
      id: '/tenant/utilities'
      path: '/utilities'
      fullPath: '/tenant/utilities'
      preLoaderRoute: typeof TenantUtilitiesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/notices': {
      id: '/tenant/notices'
      path: '/notices'
      fullPath: '/tenant/notices'
      preLoaderRoute: typeof TenantNoticesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/billing': {
      id: '/tenant/billing'
      path: '/billing'
      fullPath: '/tenant/billing'
      preLoaderRoute: typeof TenantBillingRouteImport
      parentRoute: typeof TenantRoute
    }
  }
}

interface TenantRouteChildren {
  TenantBillingRoute: typeof TenantBillingRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantNoticesRoute: typeof TenantNoticesRoute
  TenantUtilitiesRoute: typeof TenantUtilitiesRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantBillingRoute: TenantBillingRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantNoticesRoute: TenantNoticesRoute,
  TenantUtilitiesRoute: TenantUtilitiesRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingRoute: BuildingRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  MaintenanceRoute: MaintenanceRoute,
  NoticesRoute: NoticesRoute,
  RentRoute: RentRoute,
  TenantRoute: TenantRouteWithChildren,
  TenantsRoute: TenantsRoute,
  UtilitiesRoute: UtilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
